FROM node:22.12-alpine3.20

RUN apk add --no-cache bash wget unzip git aws-cli jq openssh-client curl git && \
    mkdir -p /home/node/infra && \
    chown node:node /home/node/infra && \
    wget https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip && \
    unzip terraform_1.9.5_linux_amd64.zip && \
    mv terraform /usr/local/bin/terraform && \
    rm terraform_1.9.5_linux_amd64.zip LICENSE.txt && \
    chmod +x /usr/local/bin/terraform && \
    wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.67.4/terragrunt_linux_amd64 && \
    mv terragrunt_linux_amd64 /usr/local/bin/terragrunt && \
    chmod +x /usr/local/bin/terragrunt && \
    npm install -g @go-task/cli pnpm

RUN apk add --no-cache rsync

USER node

WORKDIR /home/node/infra
